# Common
WAITING = -3
TIMEOUT = -2
END = -1
EMPTY = 0


# Cars
CAR_TYPE = 1
CAR_COLOR = 2
CAR_MILEAGE_DECISION = 3
CAR_MILEAGE = 4
PHOTO = 5
SUMMARY = 6


# Event Createion
ENTERED_NEW_EVENT_NAME = 1
ENTERED_NEW_ITEM = 2
ENTERED_MORE_OF_SAME_ITEM = 3
MORE_ITEMS_DECISION= 4
ENTERED_NEEDED_ITEM_ALLOW_MORE = 5
EVENT_CREATION_SUMMARY = 6
# Event Item Regestration
ENTERED_ITEM_TO_BRING = 7
ITEM_TO_BRING_SUMMARY = 8
